
steps:
- label: ":ruby: Rails Current"
  timeout_in_minutes: 5
  agents:
    queue: ruby
    ruby: 2.6.5
  env:
    JUNIT_OUTPUT_DIR: test/reports/current
  commands:
  - apt-get update && apt-get install -y libsqlite3-dev
  - bundle install
  - bundle exec rake db:migrate
  - bundle exec rake test
  artifact_paths:
  - test/reports/**/*
- label: ":ruby: Rails 4"
  timeout_in_minutes: 5
  agents:
    queue: ruby
    ruby: 2.6.5
  env:
    JUNIT_OUTPUT_DIR: test/reports/rails_4
  commands:
  - apt-get update && apt-get install -y libsqlite3-dev
  - bundle install
  - bundle exec appraisal install
  - bundle exec rake db:migrate
  - bundle exec appraisal rails-4 rake test
  artifact_paths:
  - test/reports/**/*
- label: ":ruby: Rails 5"
  timeout_in_minutes: 5
  agents:
    queue: ruby
    ruby: 2.6.5
  env:
    JUNIT_OUTPUT_DIR: test/reports/rails_5
  commands:
  - apt-get update && apt-get install -y libsqlite3-dev
  - bundle install
  - bundle exec appraisal install
  - bundle exec rake db:migrate
  - bundle exec appraisal rails-5 rake test
  artifact_paths:
  - test/reports/**/*
- label: ":ruby: Rails 6"
  timeout_in_minutes: 5
  agents:
    queue: ruby
    ruby: 2.6.5
  env:
    JUNIT_OUTPUT_DIR: test/reports/rails_6
  commands:
  - apt-get update && apt-get install -y libsqlite3-dev
  - bundle install
  - bundle exec appraisal install
  - bundle exec rake db:migrate
  - bundle exec appraisal rails-6 rake test
  artifact_paths:
  - test/reports/**/*

- wait: ~
  continue_on_failure: true

- label: Test Summary
  timeout_in_minutes: 5
  agents:
    queue: ruby
    ruby: 2.6.5
  plugins:
  - invoca/test-summary#invoca-integration:
      inputs:
      - label: Unit Tests
        artifact_path: test/reports/current/*.xml
        type: junit
      - label: Rails 4 Unit Tests
        artifact_path: test/reports/rails_4/*.xml
        type: junit
      - label: Rails 5 Unit Tests
        artifact_path: test/reports/rails_5/*.xml
        type: junit
      - label: Rails 6 Unit Tests
        artifact_path: test/reports/rails_6/*.xml
        type: junit
      run_without_docker: true
