#!/usr/bin/groovy
@Library('jenkins-pipeline@v0.4.4')
import com.invoca.utils.*;

pipeline {
  agent {
    kubernetes {
      defaultContainer 'ruby'
      yamlFile '.jenkins/ruby_build_pod.yml'
    }
  }

  environment { GITHUB_TOKEN = credentials('github_token') }

  stages {
    stage('Setup') {
      steps {
        updateGitHubStatus('clean-build', 'pending', "Running unit tests")
        sh 'bundle install'
        sh 'bundle exec appraisal install'
        sh 'bundle exec rake db:migrate'
      }
    }

    stage('Unit Tests') {
      steps { sh "bundle exec rake test" }
      post  { always { junit 'test/reports/*.xml' } }
    }
  }

  post {
    success { updateGitHubStatus('clean-build', 'success', "Running unit tests") }
    failure { updateGitHubStatus('clean-build', 'failure', "Running unit tests") }
  }
}

void updateGitHubStatus(String context, String status, String description) {
  gitHubStatus([
    repoSlug:    'Invoca/aggregate',
    sha:         env.GIT_COMMIT,
    description: description,
    context:     context,
    targetURL:   env.RUN_DISPLAY_URL,
    token:       env.GITHUB_TOKEN,
    status:      status
  ])
}
