---
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/aggregate: 'true'
  namespace: jenkins
  name: aggregate
spec:
  containers:
  - name: ruby
    image: ruby:2.6.1
    tty: true
    resources:
      requests:
        memory: "100Mi"
    command:
      - cat

