name: Pipeline
on: [push]
jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2, 3.3]
        gemfile:
        - Gemfile
        - gemfiles/activerecord_6_0.gemfile
        - gemfiles/activerecord_6_1.gemfile
        - gemfiles/activerecord_7_0.gemfile
        - gemfiles/activerecord_7_1.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.2.29
        bundler-cache: true
    - run: bundle exec rails db:migrate
    - run: bundle exec rake test
  check:
    if: always()
    needs:
      - tests
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
