---
name: Update Appraisals
on:
  schedule:
    - cron: '0 8 * * 0' # Every Sunday at 8AM UTC
  workflow_dispatch:

permissions: write-all

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # Ensure we don't accumulate undesired Gemfiles
      - name: Delete Existing Appraisal Gemfiles
        run: rm gemfiles/*.gemfile

      - name: Update Appraisal Gemfiles
        run: bundle exec appraisal install

      - name: Open a Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GEM_UPDATE_GIT_TOKEN }}
          author: "gem-update <gem-update@users.noreply.github.com>"
          title: "non-production: Update Appraisal Gemfiles"
          body: "This PR updates the Appraisal Gemfiles."
          commit-message: "non-production: Update Appraisal Gemfiles"
          branch: update-appraisals
          branch-suffix: timestamp
          base: ${{ github.event.repository.default_branch }}
          add-paths: "gemfiles/*"
